hotelproject/hba/hba/urls.py
from django.contrib import admin
from django.urls import path, include
import hba.myviews as myviews
from user import views
from rooms import urls as rooms_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', myviews.index, name='index'),
    #path('login_register/', userviews.login_register),
    path('users/', include('user.urls', namespace='users')),
    path('rooms/', include(rooms_urls, namespace='rooms')),
    
]

hotelproject/hba/rooms/urls.py
from django.urls import path
from . import views
from .views import user_bookings, delete_booking

app_name = 'rooms'

urlpatterns = [
    path('book-room/', views.book_room, name='book_room'),
    path('room-types/', views.room_types, name='room_types'),
    path('success-page/', views.success_page, name='success_page'),
    path('user_bookings/', user_bookings, name='user_bookings'),
    path('delete_booking/<int:booking_id>/', delete_booking, name='delete_booking'),

]

hotelproject/hba/user/urls.py
from django.urls import path
from .views import login_user, register_user, GuestUpdateView, success_update_view

app_name = 'user'

urlpatterns = [
    path('login_user', login_user, name="login"),
    path('register_user', register_user, name="register"),
    path('profile', GuestUpdateView.as_view(), name="profile"),
    path('success_update', success_update_view, name='success_update'),

]

hotelproject/hba/templates/booking_form.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Booking Form HTML Template</title>

    <!-- Google font -->
    <link href="https://fonts.googleapis.com/css?family=Raleway:400,700" rel="stylesheet">

    <!-- Bootstrap -->
    <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}" />

    <!-- Custom stlylesheet -->
    <link rel="stylesheet" href="{% static 'booking.css' %}" />

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>
    <div id="booking" class="section">
        <div class="section-center">
            <div class="container">
                <div class="row">
                    <div class="booking-form">
                        <div class="form-header">
                            <h1>Make your reservation</h1>
                        </div>
                        <form method="post" action="{% url 'rooms:book_room' %}">
                            {% csrf_token %}

                            <div class="form-group">
                                <label for="username">Username</label>
                                <input class="form-control" type="text" id="username" name="user_name" placeholder="Username" required>
                            </div>

                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="check-in">Check In</label>
                                        <input class="form-control" type="date" id="check-in" name="check_in" title="Select check-in date" required>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="check-out">Check Out</label>
                                        <input class="form-control" type="date" id="check-out" name="check_out" title="Select check-out date" required>
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label for="num-rooms">Number of Rooms</label>
                                        <select class="form-control" id="num-rooms" name="num_rooms" title="Select the number of rooms" required>
                                            <option value="" selected hidden>no of rooms</option>
                                            <option>1</option>
                                            <option>2</option>
                                            <option>3</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label for="num-adults">Number of Adults</label>
                                        <select class="form-control" id="num-adults" name="num_adults" title="Select the number of adults" required>
                                            <option value="" selected hidden>no of adults</option>
                                            <option>1</option>
                                            <option>2</option>
                                            <option>3</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label for="num-children">Number of Children</label>
                                        <select class="form-control" id="num-children" name="num_children" title="Select the number of children" required>
                                            <option value="" selected hidden>no of children</option>
                                            <option>0</option>
                                            <option>1</option>
                                            <option>2</option>
                                        </select>
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="email">Email</label>
                                        <input class="form-control" type="email" id="email" name="email" placeholder="Enter your Email">
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="phone">Phone</label>
                                        <input class="form-control" type="tel" id="phone" name="phone" placeholder="Enter your Phone">
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="room-type">Room Type</label>
                                <select class="form-control" id="room-type" name="room_type" required>
                                    {% for room_type in room_types %}
                                        <option value="{{ room_type.id }}">{{ room_type.name }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            

                            <div class="form-btn">
                                <button type="submit" class="submit-btn">Book Now</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

</html>

hotelproject/hba/templates/login_register.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'login.css' %}">
</head>
<body>
{% block content %}
    {% if messages %}
    <div class="messages">
        <ul class="messages-list">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    </div>
    {% endif %}

    <div class="hero">
        <div class="form-box">
            <div class="button-box">
                <div id="btn"></div>
                <div class="button-container">
                    <button type="button" class="toggle-btn" onclick="login()">Login</button>
                    <button type="button" class="toggle-btn" onclick="register()">Register</button>
                </div>
            </div>
            <div class="social-icons">
                <a href="facebook.com"><img src="{% static 'image/fb.png' %}" alt="fb"></a>
                <img src="{% static 'image/tw.png' %}" alt="tw">
                <img src="{% static 'image/gp.png' %}" alt="gp">
            </div>
            <form action="{% url 'user:login' %}" method="post" id="login" class="input-group">
                {% csrf_token %}
                <label for="login-username">Username:</label>
                <input type="text" class="input-field" id="login-username" name="username" placeholder="Username" required>
                <br>
                <label for="login-password">Password:</label>
                <input type="password" class="input-field" id="login-password" name="password" placeholder="Password" required>
                <input type="checkbox" class="check-box"><span>Remember Password</span>
                <button type="submit" class="submit-btn">Login</button>
            </form>
            <form action="{% url 'users:register' %}" method="POST" class="input-group" id="register">
                {% csrf_token %}
                <label for="register-username">Username:</label>
                <input class="input-field" type="text" name="username" id="register-username" maxlength="150" required>
                <label for="register-first-name">First name:</label>
                <input class="input-field" type="text" name="first_name" id="register-first-name" maxlength="50" required>
                <label for="register-last-name">Last name:</label>
                <input class="input-field" type="text" name="last_name" id="register-last-name" maxlength="50" required>    
                <label for="register-email">Email:</label>
                <input class="input-field" type="email" name="email" id="register-email" required>
                <label for="register-password">Password:</label>
                <input class="input-field" type="password" name="password1" id="register-password" required>

                <label for="register-password2">Confirm Password:</label>
                <input class="input-field" type="password" name="password2" id="register-password2" required>
                <button type="submit" class="submit-btn">Register</button>
            </form>
        </div>
    </div>
{% endblock content %}

<script>
    var x = document.getElementById("login");
    var y = document.getElementById("register");
    var z = document.getElementById("btn");

    function register() {
        x.style.left = "-400px";
        y.style.left = "70px";
        z.style.left = "110px";
    }

    function login() {
        x.style.left = "50px";
        y.style.left = "450px";
        z.style.left = "0";
    }
</script>
</body>
</html>

hotelproject/hba/templates/profile.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Profile</title>
    <link rel="stylesheet" href="{% static 'user.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<body>
    
    <div class="container">
        <div class="profile-box">
            <img src="{% static 'image/a.png' %}" alt="">
            <hr />
            <h1 class="text-center">{{ request.user|upper }}</h1>
            <form method="post" action="{% url 'user:profile' %}">
              {% csrf_token %}
              {{ user_form.as_p }}
              <input type="submit" class="btn btn-block btn-primary" value="Update Profile" />
            </form>
            <div class="About">
              <ul class="flex-container">
                  <a href="{% url 'rooms:user_bookings' %}" class="flex2">
                      <span>Bookings</span>
                  </a>
                  <a href="{% url 'index' %}" class="flex2">
                      <span>Home</span>
                  </a>
              </ul>
          </div>
          
        </div>

</body>

</html>

hotelproject/hba/templates/profile_update.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Profile</title>
    <link rel="stylesheet" href="{% static 'profile.css' %}">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<body>
    <header class="header">
        <div class="contaiinern">
          <nav class="navbar flex1">
            <div class="sticky_logo logo">
              <img src="{% static 'image/logo.png'%}" alt="" width= "120px";
              height= "50px">
            </div>
    
            <ul class="nav-menu">
              <li> <a href="#home">Home</a> </li>
              <li> <a href="#about">about</a> </li>
              <li> <a href="#room">room</a> </li>
              <li> <a href="#services">services</a> </li>
              <li> <a href="#testimonials">testimonials</a> </li>
              <li> <a href="#gallary">gallary</a> </li>
              <li> <a href="#blog">blog</a> </li>
              <li> <a href="#contact">contact</a> </li>
              <li> <a href="{% url 'user:profile' %}">profile</a> </li>
              <li><a href="{% url 'user:login' %}">Login</a></li>    
            </ul>
            <div class="hamburger">
              <span class="bar"></span>
              <span class="bar"></span>
              <span class="bar"></span>
            </div>
    
            <div class="head_contact">
              <i class="fas fa-phone-volume"></i>
              <span>+971 4 241 9600</span>
            </div>
          </nav>
        </div>
      </header>

    <div class="container">
        <div class="box">
            <img src="assets/rdj.jpeg" alt="">
            <hr />
            <h1 class="text-center">{{ request.user|upper }}</h1>
            <form method="POST" enctype="multipart/form-data">
            {% csrf_token %} {{user_form}}
              <input
                type="submit"
                class="btn btn-block btn-primary"
                value="Update Profile"
              />
            </form>  
            <ul>
              <li><i style="font-size:24px" class="fa"></i>
                  <i style="font-size:24px" class="fa"></i>
                  <i style="font-size:24px" class="fa"></i></li>
            </ul>
        </div>
        <div class="About">
            <ul>
                <h1>My Bookings</h1>
                
                <a href="{% url 'user_bookings' %}" class="flex2">
                    <span>Bookings</span>
                </a>
            </ul>
        </div>
        <a href="{% url 'index' %}" class="flex2">
          <span>Home</span>
        </a>
    </div>
</body>
</html>

hotelproject/hba/templates/success_page.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'success.css' %}">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Success Page</title>
</head>
<body>
    <div class="main_container">
        <div class="success">
            <h1>Booking Successful</h1>
            <p><strong>Thank you for your booking! Your reservation has been successfully submitted.</strong></p>
            <a href="{% url 'index' %}" class="flex2">
                <span>Home</span>
            </a>
        </div>        
    </div>
</body>
</html>

hotelproject/hba/templates/success_update.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'success.css' %}">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Success Page</title>
</head>
<body>
    <div class="main_container">
        <div class="success">
            <h1>Update Successful</h1>
            <p><strong>Thank you for your Updates!</strong></p>
            <a href="{% url 'index' %}" class="flex2">
                <span>Home</span>
            </a>
            <a href="{% url 'user:profile' %}" class="flex2">
                <span>Profile</span>
            </a>
        </div>        
    </div>
</body>
</html>

hotelproject/hba/templates/user_bookings.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Profile</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <style>
        body {
            background-image: url("/static/image/home.png");
            font-family: Arial, sans-serif;
            background-color: #f1f1f1;
            margin: 0; 
            padding: 0;
            color:black;
            background-size: cover;
        }

        header {
            text-align: center;
            padding: 10px 0;
        }

        .container1{
            max-width: 180px;
            margin: 30px auto;
            background-color: 	#8d18ccb1;
            color:white;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        .container {
            max-width: 800px;
            margin: 250px  auto 0;
            background-color: white;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        .nav-menu{
            display: flex;
            justify-content: space-around;            
        }
        .nav-menu a {
            padding-right: 40px;
            text-decoration: none;
            font-weight: 600;
            color: black;
        }

        .nav-menu li {
            list-style-type: none
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }

        th, td {
            padding: 15px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }

        th {
            background-color: #f2f2f2;
        }

        tbody tr:hover {
            background-color: #f5f5f5;
        }
    </style>
</head>

<body>

    

    <div class="container">
        {% if user_bookings %}
        <table>
            <thead>
                <tr>
                    <th>Room Number</th>
                    <th>Start Date</th>
                    <th>End Date</th>
                </tr>
            </thead>
            <tbody>
                {% for booking in user_bookings %}
                    <tr>
                        <td>{{ booking.room_type.name }}</td>
                        <td>{{ booking.check_in }}</td>
                        <td>{{ booking.check_out }}</td>
                        <td>{% if booking.is_booked %}Booked{% else %}Available{% endif %}</td>
                        <td>
                            {% if booking.is_booked %}
                                <a href="{% url 'rooms:delete_booking' booking.id %}">Cancel</a>
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        {% else %}
        <p>No bookings found.</p>
        {% endif %}
    </div>
    <header class="header">
        <div class="container1">
            <nav class="navbar flex1">

    
                <ul class="nav-menu">
                    <li><a href="{% url 'index' %}">Home</a></li>
                    <li><a href="{% url 'user:profile' %}">Profile</a></li>
                </ul>

            </nav>
        </div>
    </header>
</body>

</html>